
nouns = {
    "clothing": {
        "die Kleidung (sg.)": "clothing",
        "das Kleidungsstück, -e": "piece of clothing",
        "der Anzug, Anzüge": "suit",
        "die Bluse, -n": "blouse",
        "der Gürtel, -": "belt",
        "das Hemd, -en": "shirt",
        "die Hose, -n": "pants",
        "die Jacke, -n": "jacket",
        "das Jackett, -s": "blazer",
        "das Kleid, -er": "dress",
        "die Krawatte, -n": "tie",
        "der Mantel, Mäntel": "coat",
        "der Pullover, -": "sweater",
        "der Rock, Röcke": "skirt",
        "die Socke, -n": "sock",
        "der Strumpf, Strümpfe": "stocking",
        "das T-Shirt, -s": "T-shirt",
        "der BH, -s": "bra",
        "das Unterhemd, -en": "undershirt",
        "die Unterhose, -n": "underpants",
        "die Unterwäsche (sg.)": "underwear",
        "das Fundbüro, -s": "lost and found office",
        "die Parfümerie, -n": "perfumery",
        "das Erdgeschoss, -e": "ground floor",
        "das Untergeschoss, -e": "basement",
        "der Stock (sg.)": "floor",
        "der Ring, -e": "ring",
        "der Schuh, -e": "shoe",
        "der Stiefel, -": "boot",
        "der Gummistiefel, -": "rubber boot",
        "der Handschuh, -e": "glove",
        "der Hut, Hüte": "hat",
        "der Schal, -s": "scarf",
        "der Badeanzug, Badeanzüge": "swimsuit",
        "die Badehose, -n": "swim trunks",
        "das Make-up, -s": "make-up",
        "die Mode, -n": "fashion",
        "der Schmuck (sg.)": "jewelry",
        "die Kosmetik (sg.)": "cosmetics",
        "der Koffer, -": "suitcase",
        "das Schuhgeschäft, -e": "shoe store",
        "die Kette, -n": "necklace",
        "der Schirm, -e": "umbrella",
        "die Damenmode, -n": "women's fashion",
        "die Herrenmode, -n": "men's fashion",
        "die Kinderabteilung, -en": "children's section",
        "die Größe, -n": "size",
        "der Stoff, -e": "fabric",
        "die Qualität, -en": "quality",
        "der Pulli, -s": "sweater",
        "der Verkäufer, -": "salesperson (male)",
        "die Verkäuferin, -nen": "salesperson (female)",
        "der Kunde, -n": "customer (male)",
        "die Kundin, -nen": "customer (female)",
        "die Anprobe, -n": "fitting room",
        "die Klamotten (pl.)": "clothes",
        "der Turnschuh, -e": "sneaker",
        "die Erinnerung, -en": "memory",
        "die Vorsicht (sg.)": "caution"
    },
    "furniture": {
        "der Tisch, -e": "table",
        "der Stuhl, Stühle": "chair",
        "das Bett, -en": "bed",
        "das Sofa, -s": "sofa",
        "der Schrank, Schränke": "wardrobe",
        "die Lampe, -n": "lamp",
        "das Regal, -e": "shelf",
        "der Teppich, -e": "carpet",
        "der Spiegel, -": "mirror",
        "der Sessel, -": "armchair",
        "der Kühlschrank, Kühlschränke": "refrigerator",
        "der Fernseher, -": "television"
    },
    "daily_routines": {
        "das Frühstück, -e": "breakfast",
        "das Mittagessen, -": "lunch",
        "das Abendessen, -": "dinner",
        "der Kaffee, -s": "coffee",
        "der Tee, -s": "tea",
        "der Wecker, -": "alarm clock",
        "der Zug, Züge": "train",
        "das Auto, -s": "car",
        "die Arbeit, -en": "work"
    },
    "household_items": {
        "der Teller, -": "plate",
        "die Gabel, -n": "fork",
        "das Messer, -": "knife",
        "der Löffel, -": "spoon",
        "der Topf, Töpfe": "pot",
        "die Pfanne, -n": "pan",
        "die Waschmaschine, -n": "washing machine",
        "der Staubsauger, -": "vacuum cleaner",
        "der Geschirrspüler, -": "dishwasher",
        "die Tasse, -n": "cup"
    },
    "nature_and_environment": {
        "der Baum, Bäume": "tree",
        "der Fluss, Flüsse": "river",
        "der Berg, Berge": "mountain",
        "der See, -n": "lake",
        "die Blume, -n": "flower",
        "der Himmel, -": "sky",
        "der Wald, Wälder": "forest",
        "die Sonne, -n": "sun",
        "der Regen, -": "rain",
        "der Schnee, -": "snow"
    }
}
